# Generated by Django 6.0.2 on 2026-02-12 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('customer_full_name', models.CharField(max_length=255)),
                ('receive_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('completed', 'Завершён')], default='new', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('pick_up_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.pickuppoint')),
            ],
        ),
    ]
